// Generated by tools/generate-holidays.py — do not edit by hand.
// Kenya (KE) and Uganda (UG) public holidays.
//
// FIXED_HOLIDAYS are fixed month/day rows. LUNAR_HOLIDAYS are
// moon-sighted observances (Eid al-Fitr, Eid al-Adha, Diwali)
// pinned per year with the common civic date; observe that these
// are approximate — the declared date can shift a day on either
// side depending on moon sighting. Good Friday and Easter Monday
// are *not* stored here; Model.computusEaster() derives them from
// the Gregorian computus at load, exact for any year.

var FIXED_HOLIDAYS = [
  { m:1, d:1, n:"New Year's Day", cc:"KE UG" },
  { m:1, d:26, n:"NRM Liberation Day", cc:"UG" },
  { m:2, d:16, n:"Archbishop Janani Luwum Day", cc:"UG" },
  { m:3, d:8, n:"International Women's Day", cc:"UG" },
  { m:5, d:1, n:"Labour Day", cc:"KE UG" },
  { m:6, d:1, n:"Madaraka Day", cc:"KE" },
  { m:6, d:3, n:"Martyrs' Day", cc:"UG" },
  { m:6, d:9, n:"National Heroes' Day", cc:"UG" },
  { m:10, d:9, n:"Independence Day", cc:"UG" },
  { m:10, d:10, n:"Huduma Day", cc:"KE" },
  { m:10, d:20, n:"Mashujaa Day", cc:"KE" },
  { m:12, d:12, n:"Jamhuri Day", cc:"KE" },
  { m:12, d:25, n:"Christmas Day", cc:"KE UG" },
  { m:12, d:26, n:"Boxing Day / Utamaduni Day", cc:"KE UG" },
]

var GLOBAL_HOLIDAYS = [
  { m:1, d:1, n:"New Year's Day", cc:"GLOBAL" },
  { m:3, d:8, n:"International Women's Day", cc:"GLOBAL" },
  { m:5, d:1, n:"International Workers' Day", cc:"GLOBAL" },
  { m:6, d:5, n:"World Environment Day", cc:"GLOBAL" },
  { m:12, d:10, n:"Human Rights Day", cc:"GLOBAL" },
  { m:12, d:25, n:"Christmas Day", cc:"GLOBAL" },
]

var LUNAR_HOLIDAYS = {
  2025: [
    { d:"2025-03-31", n:"Eid al-Fitr", cc:"KE UG", approx: true },
    { d:"2025-06-07", n:"Eid al-Adha", cc:"KE UG", approx: true },
    { d:"2025-10-20", n:"Diwali", cc:"KE", approx: true },
  ],
  2026: [
    { d:"2026-03-20", n:"Eid al-Fitr", cc:"KE UG", approx: true },
    { d:"2026-05-27", n:"Eid al-Adha", cc:"KE UG", approx: true },
    { d:"2026-11-08", n:"Diwali", cc:"KE", approx: true },
  ],
  2027: [
    { d:"2027-03-09", n:"Eid al-Fitr", cc:"KE UG", approx: true },
    { d:"2027-05-16", n:"Eid al-Adha", cc:"KE UG", approx: true },
    { d:"2027-10-29", n:"Diwali", cc:"KE", approx: true },
  ],
  2028: [
    { d:"2028-02-26", n:"Eid al-Fitr", cc:"KE UG", approx: true },
    { d:"2028-05-04", n:"Eid al-Adha", cc:"KE UG", approx: true },
    { d:"2028-10-17", n:"Diwali", cc:"KE", approx: true },
  ],
  2029: [
    { d:"2029-02-14", n:"Eid al-Fitr", cc:"KE UG", approx: true },
    { d:"2029-04-23", n:"Eid al-Adha", cc:"KE UG", approx: true },
    { d:"2029-11-05", n:"Diwali", cc:"KE", approx: true },
  ],
  2030: [
    { d:"2030-02-03", n:"Eid al-Fitr", cc:"KE UG", approx: true },
    { d:"2030-04-12", n:"Eid al-Adha", cc:"KE UG", approx: true },
    { d:"2030-10-26", n:"Diwali", cc:"KE", approx: true },
  ],
  2031: [
    { d:"2031-01-23", n:"Eid al-Fitr", cc:"KE UG", approx: true },
    { d:"2031-04-01", n:"Eid al-Adha", cc:"KE UG", approx: true },
    { d:"2031-11-14", n:"Diwali", cc:"KE", approx: true },
  ],
  2032: [
    { d:"2032-01-12", n:"Eid al-Fitr", cc:"KE UG", approx: true },
    { d:"2032-03-21", n:"Eid al-Adha", cc:"KE UG", approx: true },
    { d:"2032-11-03", n:"Diwali", cc:"KE", approx: true },
  ],
  2033: [
    { d:"2033-01-01", n:"Eid al-Fitr", cc:"KE UG", approx: true },
    { d:"2033-12-20", n:"Eid al-Fitr", cc:"KE UG", approx: true },
    { d:"2033-03-10", n:"Eid al-Adha", cc:"KE UG", approx: true },
    { d:"2033-10-23", n:"Diwali", cc:"KE", approx: true },
  ],
  2034: [
    { d:"2034-12-10", n:"Eid al-Fitr", cc:"KE UG", approx: true },
    { d:"2034-02-28", n:"Eid al-Adha", cc:"KE UG", approx: true },
    { d:"2034-11-11", n:"Diwali", cc:"KE", approx: true },
  ],
  2035: [
    { d:"2035-11-29", n:"Eid al-Fitr", cc:"KE UG", approx: true },
    { d:"2035-02-18", n:"Eid al-Adha", cc:"KE UG", approx: true },
    { d:"2035-10-31", n:"Diwali", cc:"KE", approx: true },
  ],
}

function fixedHolidays() {
  return FIXED_HOLIDAYS
}

function globalHolidays() {
  return GLOBAL_HOLIDAYS
}

function lunarHolidays() {
  return LUNAR_HOLIDAYS
}

function holidayTable(year) {
  var table = {}
  var rows = FIXED_HOLIDAYS.concat(GLOBAL_HOLIDAYS)
  for (var i = 0; i < rows.length; i++) {
    var row = rows[i]
    var key = String(year) + "-" + (row.m < 10 ? "0" : "") + row.m + "-" + (row.d < 10 ? "0" : "") + row.d
    if (!table[key]) table[key] = { n: row.n, cc: row.cc }
    else {
      table[key].cc += " " + row.cc
      if (table[key].n.indexOf(row.n) === -1) table[key].n += " / " + row.n
    }
  }
  var lunar = LUNAR_HOLIDAYS[year] || []
  for (var j = 0; j < lunar.length; j++) {
    var lunarRow = lunar[j]
    if (!table[lunarRow.d]) table[lunarRow.d] = { n: lunarRow.n, cc: lunarRow.cc }
    else {
      table[lunarRow.d].cc += " " + lunarRow.cc
      if (table[lunarRow.d].n.indexOf(lunarRow.n) === -1) table[lunarRow.d].n += " / " + lunarRow.n
    }
  }
  return table
}

if (typeof module !== 'undefined') {
  module.exports = {
    FIXED_HOLIDAYS: FIXED_HOLIDAYS,
    GLOBAL_HOLIDAYS: GLOBAL_HOLIDAYS,
    LUNAR_HOLIDAYS: LUNAR_HOLIDAYS,
    fixedHolidays: fixedHolidays,
    globalHolidays: globalHolidays,
    lunarHolidays: lunarHolidays,
    holidayTable: holidayTable
  }
}
