#!/usr/bin/env python3
"""Regenerate countries.js — the offline name/capital/timezone/coordinate
table that powers the myles.clock world-clock country picker.

Merges two upstream datasets:

  * mledoze/countries     — country names, capitals and capital coordinates
    (independent, officially-assigned sovereign states only);
  * moment-timezone meta  — the IANA zone list per country, each zone paired
    with its representative "LatLon" point ("Canada/NT (61.5,-101.05)").

For every country it picks the IANA zone whose representative point sits
nearest the capital — not the first entry in the list, which is not ordered
by capital (America/St_Johns leads Canada), so a blind index-zero default
would set federations to a provincial timezone. The chosen zone's current
UTC offset (minutes) and the capital's coordinates are recorded as a static
offline fallback. Live rows refresh their true offset from the Open-Meteo
weather fetch (utc_offset_seconds), which is DST-correct by construction.

Usage:
    python3 tools/generate-countries.py
    # Pin local copies instead of the network:
    #   MLEDOZE_JSON=/tmp/countries.json MOMENT_JSON=/tmp/moment.json \
    #     python3 tools/generate-countries.py
"""

import json
import os
import sys
import urllib.request
from datetime import datetime
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

MLEDOZE_URL = "https://raw.githubusercontent.com/mledoze/countries/master/dist/countries.json"
MOMENT_URL = "https://raw.githubusercontent.com/moment/moment-timezone/develop/data/meta/latest.json"
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "countries.js")


def fetch(path, url):
    if path and os.path.isfile(path):
        with open(path) as fh:
            return json.load(fh)
    with urllib.request.urlopen(url, timeout=30) as resp:
        return json.loads(resp.read().decode("utf-8"))


def zone_latlng(text):
    """Parse the "Canada/NT (61.5,-101.05)" suffix into (lat, lon) or None."""
    try:
        i = text.rfind("(")
        if i < 0:
            return None
        a, b = text[i + 1:-1].split(",")
        return float(a), float(b)
    except (ValueError, AttributeError):
        return None


def distance_sq(lat1, lon1, lat2, lon2):
    return (lat1 - lat2) ** 2 + (lon1 - lon2) ** 2


def nearest_zone(zone_names, zone_coords, lat, lon):
    """Pick the IANA zone whose representative point sits nearest the capital.
    Only used for the static fallback row; live rows get their true offset
    from the weather fetch."""
    best, best_dist = None, None
    for zn in zone_names:
        c = (zone_coords or {}).get(zn)
        if not c:
            continue
        d = distance_sq(lat or 0, lon or 0, c[0], c[1])
        if best is None or d < best_dist:
            best, best_dist = zn, d
    return best or (zone_names[0] if zone_names else None)


def offset_minutes(tz_name):
    try:
        return int(round(datetime.now().astimezone(ZoneInfo(tz_name)).utcoffset().total_seconds() / 60))
    except (ZoneInfoNotFoundError, OSError, ValueError):
        return None


def main():
    mledoze = fetch(os.environ.get("MLEDOZE_JSON", ""), MLEDOZE_URL)
    moment = fetch(os.environ.get("MOMENT_JSON", ""), MOMENT_URL)

    zones_by_cc = moment.get("countries", {})
    zone_coords = {}
    for zn, text in (moment.get("zones") or {}).items():
        c = zone_latlng(str(text or ""))
        if c:
            zone_coords[zn] = c

    rows = []
    for entry in mledoze:
        if entry.get("independent") is not True:
            continue
        if entry.get("status") != "officially-assigned":
            continue
        cca2 = entry.get("cca2")
        if not cca2:
            continue
        capital = (entry.get("capital") or [None])[0]
        if not capital:
            continue
        latlng = entry.get("latlng") or []
        if len(latlng) != 2:
            continue
        zones = (zones_by_cc.get(cca2) or {}).get("zones") or []
        if not zones:
            continue
        tz = nearest_zone(zones, zone_coords, float(latlng[0]), float(latlng[1]))
        off = offset_minutes(tz)
        if off is None:
            continue
        rows.append({
            "c": cca2,
            "n": entry["name"]["common"],
            "cap": capital,
            "tz": tz,
            "off": int(off),
            "lat": round(float(latlng[0]), 4),
            "lon": round(float(latlng[1]), 4),
        })

    rows.sort(key=lambda r: r["n"].lower())

    js = (
        "// Generated by tools/generate-countries.py — do not edit by hand.\n"
        "// Countries with their capital, primary IANA timezone, UTC offset\n"
        "// (minutes, static fallback) and capital coordinates. Live rows\n"
        "// refresh the offset from the weather fetch.\n\n"
        "var COUNTRIES = [\n"
    )
    for r in rows:
        js += (
            '  { c:"%s", n:"%s", cap:"%s", tz:"%s", off:%d, lat:%.4f, lon:%.4f },\n'
            % (r["c"], r["n"], r["cap"], r["tz"], r["off"], r["lat"], r["lon"])
        )
    js += "]\n\nif (typeof module !== 'undefined') {\n  module.exports = { COUNTRIES: COUNTRIES }\n}\n"

    with open(OUT, "w") as fh:
        fh.write(js)
    print("wrote %s (%d countries)" % (OUT, len(rows)))


if __name__ == "__main__":
    sys.exit(main())