#!/usr/bin/env python3
"""Regenerate holidays.js — the Kenya/Uganda public-holiday table the
myles.clock calendar dots up next />

divide it in three at the seams where the calendar already does:

  * FIXED_HOLIDAYS  — month/day rows shared (or nearly) by both countries on
    a written calendar. Kenya and Uganda overlap on the inherited British/
    colonial dates (New Year, Easter, Labour Day, Christmas, Boxing Day) and
    on Eid al-Fitr/Eid al-Adha for their Muslim populations, while each keeps
    its own nationalist set (Madaraka/Mashujaa/Jamhuri/Huduma/Utamaduni for
    Kenya; Luwum/NRM/Martyrs/Heroes/Independence for Uganda).
  * LUNAR_HOLIDAYS  — moon-sighted observances that cannot be computed (Eid
    al-Fitr, Eid al-Adha, Diwali). They follow the astronomical calendar and
    official sighting, so each is pinned by year with the common civic date
    and flagged "approx" — the declared date can shift a day either way.
  * Easter rows (Good Friday, Easter Monday) are NOT stored here: they are
    computed at load by Model.computusEaster() from the Gregorian computus,
    which is exact for any year and needs no table.

Computed-at-load math lives in Model.js; this file is deliberately pure data
so the calendar can stay a dumb read-out of Model. Keep the keys ASCII and
the names as-written (capitalised, no accents) — QML renders them as-is.

Usage:
    python3 tools/generate-holidays.py
"""

import json
import os
import sys

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "holidays.js")

# year -> [(iso "yyyy-mm-dd", name, country codes)]
LUNAR = {
    2025: [
        ("2025-03-31", "Eid al-Fitr", "KE UG"),
        ("2025-06-07", "Eid al-Adha", "KE UG"),
        ("2025-10-20", "Diwali", "KE"),
    ],
    2026: [
        ("2026-03-20", "Eid al-Fitr", "KE UG"),
        ("2026-05-27", "Eid al-Adha", "KE UG"),
        ("2026-11-08", "Diwali", "KE"),
    ],
    2027: [
        ("2027-03-09", "Eid al-Fitr", "KE UG"),
        ("2027-05-16", "Eid al-Adha", "KE UG"),
        ("2027-10-29", "Diwali", "KE"),
    ],
    2028: [
        ("2028-02-26", "Eid al-Fitr", "KE UG"),
        ("2028-05-04", "Eid al-Adha", "KE UG"),
        ("2028-10-17", "Diwali", "KE"),
    ],
    2029: [
        ("2029-02-14", "Eid al-Fitr", "KE UG"),
        ("2029-04-23", "Eid al-Adha", "KE UG"),
        ("2029-11-05", "Diwali", "KE"),
    ],
    2030: [
        ("2030-02-03", "Eid al-Fitr", "KE UG"),
        ("2030-04-12", "Eid al-Adha", "KE UG"),
        ("2030-10-26", "Diwali", "KE"),
    ],
    2031: [
        ("2031-01-23", "Eid al-Fitr", "KE UG"),
        ("2031-04-01", "Eid al-Adha", "KE UG"),
        ("2031-11-14", "Diwali", "KE"),
    ],
    2032: [
        ("2032-01-12", "Eid al-Fitr", "KE UG"),
        ("2032-03-21", "Eid al-Adha", "KE UG"),
        ("2032-11-03", "Diwali", "KE"),
    ],
    2033: [
        ("2033-01-01", "Eid al-Fitr", "KE UG"),
        ("2033-12-20", "Eid al-Fitr", "KE UG"),
        ("2033-03-10", "Eid al-Adha", "KE UG"),
        ("2033-10-23", "Diwali", "KE"),
    ],
    2034: [
        ("2034-12-10", "Eid al-Fitr", "KE UG"),
        ("2034-02-28", "Eid al-Adha", "KE UG"),
        ("2034-11-11", "Diwali", "KE"),
    ],
    2035: [
        ("2035-11-29", "Eid al-Fitr", "KE UG"),
        ("2035-02-18", "Eid al-Adha", "KE UG"),
        ("2035-10-31", "Diwali", "KE"),
    ],
}

# (month, day, name, country codes)
FIXED = [
    (1, 1, "New Year's Day", "KE UG"),
    (1, 26, "NRM Liberation Day", "UG"),
    (2, 16, "Archbishop Janani Luwum Day", "UG"),
    (3, 8, "International Women's Day", "UG"),
    (5, 1, "Labour Day", "KE UG"),
    (6, 1, "Madaraka Day", "KE"),
    (6, 3, "Martyrs' Day", "UG"),
    (6, 9, "National Heroes' Day", "UG"),
    (10, 9, "Independence Day", "UG"),
    (10, 10, "Huduma Day", "KE"),
    (10, 20, "Mashujaa Day", "KE"),
    (12, 12, "Jamhuri Day", "KE"),
    (12, 25, "Christmas Day", "KE UG"),
    (12, 26, "Boxing Day / Utamaduni Day", "KE UG"),
]


def main():
    header = (
        "// Generated by tools/generate-holidays.py — do not edit by hand.\n"
        "// Kenya (KE) and Uganda (UG) public holidays.\n"
        "//\n"
        "// FIXED_HOLIDAYS are fixed month/day rows. LUNAR_HOLIDAYS are\n"
        "// moon-sighted observances (Eid al-Fitr, Eid al-Adha, Diwali)\n"
        "// pinned per year with the common civic date; observe that these\n"
        "// are approximate — the declared date can shift a day on either\n"
        "// side depending on moon sighting. Good Friday and Easter Monday\n"
        "// are *not* stored here; Model.computusEaster() derives them from\n"
        "// the Gregorian computus at load, exact for any year.\n"
    )

    js = header + "\nvar FIXED_HOLIDAYS = [\n"
    for (m, d, name, cc) in FIXED:
        js += "  { m:%d, d:%d, n:%s, cc:\"%s\" },\n" % (m, d, json.dumps(name), cc)
    js += "]\n\n"

    js += "var LUNAR_HOLIDAYS = {\n"
    for year in sorted(LUNAR):
        js += "  %d: [\n" % year
        for (iso, name, cc) in LUNAR[year]:
            js += "    { d:\"%s\", n:%s, cc:\"%s\", approx: true },\n" % (iso, json.dumps(name), cc)
        js += "  ],\n"
    js += "}\n\n"

    js += "if (typeof module !== 'undefined') {\n"
    js += "  module.exports = { FIXED_HOLIDAYS: FIXED_HOLIDAYS, LUNAR_HOLIDAYS: LUNAR_HOLIDAYS }\n"
    js += "}\n"

    with open(OUT, "w") as fh:
        fh.write(js)
    print("wrote %s (lunar years %d..%d, fixed rows %d)"
          % (OUT, min(LUNAR), max(LUNAR), len(FIXED)))


if __name__ == "__main__":
    sys.exit(main())
